<div class="container">

    <h3 class="teal-text darken-4-text" style="font-weight:lighter;">Inclui nova Classe</h3>
    <div class="row">
        <form action="save_classes" method="post">
            <div class="input-field col s12">
                <input id="class_name" type="text" class="validate" name="class_name">
                <label for="class_name">Nome da Classe</label>
            </div>
            <div class="input-field col s12">
                <input id="class_description" type="text" class="validate" name="class_description">
                <label for="class_description">Descrição</label>
            </div>
            <button class="btn waves-effect waves-light" type="submit">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
    <?php ?>
</div>