<div class="container">

    <h3 class="teal-text darken-4-text" style="font-weight:lighter;">Inclui nova Sub-Classe</h3>

    <div class="row">
        <form action="save_subclasses" method="post">
            <div class="input-field col s12">
                <select name="id_movement_class">
                    <option value="" disabled selected>Choose your option</option>
                    <?php foreach ($this->viewData->classes as $class) { ?>
                        <option value="<?= $class['IDMOVEMENT_CLASS'] ?>"><?= $class['class_name'] ?></option>
                    <?php } ?>

                </select>
                <label>Classe</label>
            </div>
            <div class="input-field col s12">
                <input id="subclass_name" type="text" class="validate" name="subclass_name">
                <label for="subclass_name">Nome da Sub-Classe</label>
            </div>
            <div class="input-field col s12">
                <input id="subclass_description" type="text" class="validate" name="subclass_description">
                <label for="subclass_description">Descrição</label>
            </div>
            <button class="btn waves-effect waves-light" type="submit">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>