<div class="container">

    <h3 class="teal-text darken-4-text" style="font-weight:lighter;">Inclui novo cartão</h3>

    <div class="row">
        <form action="getData" method="post">
            <div class="input-field col s12">
                <input id="card_number" type="text" class="validate" name="card_number">
                <label for="card_number">Número do cartão</label>
            </div>
            <div class="input-field col s12">
                <select name="card_operator">
                    <option value="" disabled selected>Choose your option</option>
                    <option value="visa">Visa</option>
                    <option value="mastercard">Mastercard</option>
                    <option value="elo">Elo</option>
                    <option value="amex">American Express</option>
                </select>
                <label>Bandeira</label>
            </div>
            <div class="input-field col s6">
                <input id="pay_date" type="text" class="validate" name="pay_date">
                <label for="pay_date">Data de vencimento</label>
            </div>
            <div class="input-field col s6">
                <input id="close_date" type="text" class="validate" name="close_date">
                <label for="close_date">Data de fechamento</label>
            </div>
            <button class="btn waves-effect waves-light" type="submit">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>