<div class="container">

    <h3 class="teal-text darken-4-text" style="font-weight:lighter;">Inclui nova Classe</h3>

    <div class="row">
        <form action="" method="post">
            <div class="input-field col s12">
                <input id="movement_class" type="text" class="validate">
                <label for="movement_class">Nome da Classe</label>
            </div>
            <div class="input-field col s12">
                <input id="class_description" type="text" class="validate">
                <label for="class_description">Descrição</label>
            </div>
        </form>
    </div>
</div>