<div class="container">

    <h3 class="teal-text darken-4-text" style="font-weight:lighter;">Inclui nova Sub-Classe</h3>

    <div class="row">
        <form action="getData" method="post">
            <div class="input-field col s12">
                <select name="class">
                    <option value="" disabled selected>Choose your option</option>
                    <option value="1">Option 1</option>
                    <option value="2">Option 2</option>
                    <option value="3">Option 3</option>
                </select>
                <label>Classe</label>
            </div>
            <div class="input-field col s12">
                <input id="movement_class" type="text" class="validate" name="movement_class">
                <label for="movement_class">Nome da Sub-Classe</label>
            </div>
            <div class="input-field col s12">
                <input id="class_description" type="text" class="validate" name="class_description">
                <label for="class_description">Descrição</label>
            </div>
            <button class="btn waves-effect waves-light" type="submit">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>
</div>