<div class="container">

    <h3 class="teal-text darken-4-text center-align" style="font-weight:lighter;">Gerenciar cartões</h3>

    <div class="row">
        <a href="./list_cards" class="btn waves-effect waves-light col s12 m6 offset-m3" type="submit">Listar Cartões
            <i class="material-icons right">list</i>
        </a>
    </div>
    <div class="row">
        <a href="./add_card" class="btn waves-effect waves-light col s12 m6 offset-m3" type="submit">Adicionar Cartão
            <i class="material-icons right">add_circle_outline</i>
        </a>
    </div>
    <div class="row">
        <a href="/" class="btn waves-effect waves-light col s12 m6 offset-m3" type="submit">Voltar ao Inicio
            <i class="material-icons right">keyboard_backspace</i>
        </a>
    </div>

</div>