<div class="container">
    <h3 class="teal-text darken-4-text"><?php echo date('l jS \of F Y'); ?></h3>

    <hr>

    <div class="row">
        <div class="col s12 m6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Saldo atual</span>
                    <p style="font-size: 32px; font-weight:lighter;">R$ 10.000.00</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>

        <div class="col s12 m6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Próximos movimentos:</span>
                    <table>
                        <thead>
                            <tr>
                                <th>Data</th>
                                <th>Titulo</th>
                                <th>Valor</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>21/01/2023</td>
                                <td>Faxineira</td>
                                <td><span>(-) </span>600.00</td>
                            </tr>
                            <tr>
                                <td>21/01/2023</td>
                                <td>Premio Loteria</td>
                                <td><span>(+) </span>999000.00</td>
                            </tr>
                            <tr>
                                <td>21/01/2023</td>
                                <td>Faxineira</td>
                                <td><span>(-) </span>600.00</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
    </div>
</div>