<div class="container">

    <h3 class="teal-text darken-4-text" style="font-weight:lighter;">Inclui novo lançamento</h3>


    <form action="getDataAccount" method="post">
        <div class="row">

            <label class="input-field col s2">
                <input class="with-gap" name="movement_type" type="radio" value="D" />
                <span>Débito</span>
            </label>
            <label class="input-field col s2">
                <input class="with-gap" name="movement_type" type="radio" value="C" />
                <span>Crédito</span>
            </label>
        </div>

        <div class="input-field col s12">
            <input id="description" type="text" class="validate" name="description">
            <label for="description">Descrição</label>
        </div>
        <div>
            <h5 class="teal-text darken-4-text" style="font-weight:lighter;">Método de pagamento</h5>
            <div class="divider"></div>
            <div class="row">
                <label class="input-field col s2">
                    <input class="with-gap" name="pay_method" type="radio" value="M" />
                    <span>Dinheiro</span>
                </label>
                <label class="input-field col s2">
                    <input id="credit-card" class="with-gap" name="pay_method" type="radio" value="C" />
                    <span>Cartão de Crédito</span>
                </label>
                <div id="card">
                    <div class="input-field col s6">
                        <select name="id_credit_card" class="card">
                            <option value="" disabled selected>Selecione o cartão</option>
                            <?php foreach ($this->viewData->cards as $card) {
                                $card_show = $card['card_operator'] . '-' . substr($card['card_number'], -4, 4) ?>
                                <option value=""><?= $card_show ?></option>

                            <?php } ?>
                        </select>
                        <label>Cartão</label>
                    </div>
                    <div class="input-field col s2">
                        <input id="installments" type="text" class="validate" name="installments">
                        <label for="installments">Parcelas</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <input id="value" type="text" class="validate" name="value">
                <label for="value">Valor</label>
            </div>
            <div class="input-field col s6">
                <input type="text" class="datepicker" name="pay_date">
                <label for="value">Data de Pagamento</label>
            </div>
        </div>
        <div class="row">
            <!-- <div class="input-field col s6">
                <select name="id_movement_class" class="class">
                    <option value="" disabled selected>Selecione a Classe</option>
                    <?php foreach ($this->viewData->classes as $class) { ?>
                        <option value="<?= $class['IDMOVEMENT_CLASS'] ?>"><?= $class['class_name'] ?></option>
                    <?php } ?>
                </select>
                <label>Classe</label>
            </div> -->
            <div class="input-field col s6">
                <select id="select_subclass" name="id_movement_subclass" class="subclass">
                    <option value="" disabled selected>Selecione a Subclasse</option>
                    <?php foreach ($this->viewData->subclasses as $subclass) { ?>
                        <option value="<?= $subclass['IDMOVEMENT_SUBCLASS'] ?>"><?= $subclass['subclass_name'] ?></option>
                    <?php } ?>
                </select>
                <label>Sub-classe</label>
            </div>
            <div class="show-classes">
                <?php foreach ($this->viewData->classes as $class) { ?>
                    <p> </p>
                <?php } ?>
            </div>
        </div>
        <button class="btn waves-effect waves-light" type="submit">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
</div>

<script>
    let subclass_value;
    let pay_method = document.getElementsByName('pay_method');
    let radio = document.getElementById('card');
    pay_method[0].addEventListener('click', () => {
        radio.style.display = 'none';
    })
    pay_method[1].addEventListener('click', () => {
        radio.style.display = 'block';
    })
    let subclass_select = document.getElementById('select_subclass');
    subclass_select.addEventListener('change', () => {
        subclass_value = subclass_select.value;
        console.log(subclass_value);
    })
</script>