<!DOCTYPE html>
<html>

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="./css/materialize.min.css" media="screen,projection" />

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="/add_class">Adicionar Classe</a></li>
        <li><a href="/add_subclass">Adicionar Sub-classe</a></li>
        <li><a href="/add_card">Adicionar Cartão</a></li>
        <li class="divider"></li>
        <li><a href="#!">three</a></li>
    </ul>
    <nav>
        <div class="nav-wrapper teal lighten-3">
            <a href="/" class="brand-logo">Controle Financeiro</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="addAccount">Novo Lançamento</a></li>
                <li><a href="badges.html">Components</a></li>
                <li><a href="collapsible.html">Javascript</a></li>
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Administração<i class="material-icons right">arrow_drop_down</i></a></li>
                <li><a class="waves-effect waves-light btn">Login</a></li>
            </ul>
        </div>
    </nav>

    <ul id="dropdown_mobile" class="dropdown-content">
        <li><a href="/add_class">Adicionar Classe</a></li>
        <li><a href="/add_subclass">Adicionar Sub-classe</a></li>
        <li><a href="/add_card">Adicionar Cartão</a></li>
        <li class="divider"></li>
        <li><a href="#!">three mobile</a></li>
    </ul>

    <ul class="sidenav" id="mobile-demo">
        <li><a href="addAccount">Novo Lançamento</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">Javascript</a></li>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown_mobile">Administração<i class="material-icons right">arrow_drop_down</i></a></li>
        <li><a class="waves-effect waves-light btn">Login</a></li>

    </ul>
    <?php $this->content() ?>

    <!--JavaScript at end of body for optimized loading-->
    <script src="./js/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="./js/materialize.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelectorAll('.sidenav');
            let instances = M.Sidenav.init(el, {
                edge: 'right'
            });
        });
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelectorAll('.dropdown-trigger');
            let instances = M.Dropdown.init(el);
        });
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelectorAll('select');
            let instances = M.FormSelect.init(el);
        });
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelector('.card');
            let instances = M.FormSelect.init(el);
        });
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelector('.class');
            let instances = M.FormSelect.init(el);
        });
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelector('.subclass');
            let instances = M.FormSelect.init(el);
        });
        document.addEventListener('DOMContentLoaded', function() {
            let el = document.querySelectorAll('.datepicker');
            let instances = M.Datepicker.init(el);
        });
    </script>
</body>

</html>